services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app
    restart: unless-stopped
    networks:
      - football-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    volumes:
      - ../frontend/public:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - football-network

networks:
  football-network:
    driver: bridge